repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        exclude: "docs/.*"
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md]
        exclude: "docs/.*"
      - id: check-json
        exclude: "docs/.*"
      - id: check-yaml
        args: [ --unsafe ]
        exclude: "docs/.*"
      - id: check-added-large-files
        exclude: "docs/.*"
      - id: check-ast
        exclude: "docs/.*"
      - id: debug-statements
      # - id: double-quote-string-fixer
      # - id: name-tests-test
      - id: requirements-txt-fixer
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5
    hooks:
      - id: ruff
        args: [ --fix ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        verbose: true
        args: [--show-error-codes, --explicit-package-bases]
        additional_dependencies: ['types-requests', 'pydantic']
