repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
        exclude: "docs/.*"
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md]
        exclude: "docs/.*"
      - id: check-json
        exclude: "docs/.*"
      - id: check-yaml
        args: [ --unsafe ]
        exclude: "docs/.*"
      - id: check-added-large-files
        exclude: "docs/.*"
      - id: check-ast
        exclude: "docs/.*"
  - repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.800
    hooks:
      - id: mypy
        pass_filenames: false
  - repo: https://github.com/pycqa/pydocstyle
    rev: 5.1.1
    hooks:
      - id: pydocstyle
        pass_filenames: false
