name: Run Black
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  runsBlack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - run: pip install black
      - run: black .
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: format code with black
          title: Black Formatting
          body: format code with black
          branch: black-format
